name: example
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo hello world

  build_skim: 
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow_failure }} 
    container: rootproject/root-conda:${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix: 
        version: [6.18.04, latest]
        allow_failure: [false]
        include: 
          - version: latest
            allow_failure: true
    steps: 
      - name: checkout repository
        uses: actions/checkout@v2

      - run: |
          COMPILER=$(root-config --cxx) 
          FLAGS=$(root-config --cflags --libs)
          $COMPILER -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx $FLAGS 

